config/routes.rb
Rails.application.routes.draw do
  get 'reviews/index'
  get 'salons/index'
  #devise_for :users
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

  mount StripeEvent::Engine, at: '/stripe-webhooks'

  root to: 'pages#home'
  get "legal", to: 'pages#legal'
  get "about", to: 'pages#about'
  get "contact", to: 'pages#contact'
  resources :reviews do
    match '/scrape', to: 'reviews#scrape', via: :post, on: :collection
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


 resources :salons,  only: [:index]

  resources :epilations do
    resources :order_items, only: [:create, :update, :destroy]
  end

  resource :contacts, only: [:new, :create] do
    get "/thanks" => "contacts#thanks"
  end
  #resources :epilations, only: [:index, :show, :new, :edit, :update, :create, :destroy]
  # get "epilations", to: "epilations#index"
  # get "epilations/new", to: "epilations#new"
  # post "epilations", to: "epilations#create"
  # get "epilations/:id/edit", to: "epilations#edit"
  # patch "epilations/:id", to: "epilations#update"

  resources :massages do
    resources :order_items, only: [:create, :update, :destroy]
  end

  #resources :massages, only: [:index, :show, :new, :edit, :update, :create, :destroy]
  #get "massages", to: "massages#index"

  resources :maquillages do
    resources :order_items, only: [:create, :update, :destroy]
  end
  #resources :maquillages, only: [:index, :show, :new, :edit, :update, :create, :destroy]
  #get "maquillages", to: "maquillages#index"

  resources :soinvisages do
    resources :order_items, only: [:create, :update, :destroy]
  end
  #resources :soinvisages, only: [:index, :show, :new, :edit, :update, :create, :destroy]
  #get "soinvisages", to: "soinvisages#index"

  # Faut t'il plutot nester ?
  # resources :epilations, :massages, :maquillages, :soinvisages do
  #resources :order_items, only: [:create, :update, :destroy]
  # end
  resources :orders, only: [:index, :show, :destroy]

  resources :carts, only: [:index]
  resources :carts, only: [:new], as: :order do
    resources :payments, only: [:new]
  end

  # get '*unmatched_route', to: 'application#raise_not_found'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
    
     <div class="footer">
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-md-3 item">
                        <h3>Services</h3>
                        <ul>
                           <li><%= link_to "Epilations", epilations_path %></li>
                            <li><%= link_to "Massages", massages_path %></li>
                            <li><%= link_to "Soins", soinvisages_path %></li>
                            <li><%= link_to "Maquillage Permanent", maquillages_path %></li>

                        </ul>
                    </div>
                    <div class="col-sm-6 col-md-3 item">
                        <h3>A Propos</h3>
                        <ul>
                            <li><%= link_to "Mentions légales", legal_path%></li>
                            <li><%= link_to "Contact", salons_path%></li>
                            <li><%= link_to "Login", new_user_session_path %></li>
                        </ul>
                    </div>
                    <div class="col-md-6 item text">
                        <h3>Relook Esthetique</h3>
                        <p>Relook Esthétique, à Tarascon, est un institut spécialisé dans le maquillage permanent. <br />Vous souhaitez retrouver des lèvres sensuelles ? Un regard intense ? <br />Accordez-vous une pause beauté chez Relook Esthétique. Nous vous proposons un maquillage naturel et harmonieux en toute circonstance.</p>
                    </div>
                    <div class="col item social"><a href="https://www.facebook.com/relookesthetique/"><i class="fab fa-facebook"></i></a></div>
                </div>
                <p class="copyright">Berty's Angels © 2021</p>
            <div class="col item social"><a href="https://github.com/delarita"><i class="fab fa-github"></i></a><a href="https://github.com/berty75"><i class="fab fa-github"></i></a><a href="https://github.com/alexorciste"><i class="fab fa-github"></i></i></a></div>
            </div>
        </footer>
    </div>   
    
    
    

app/views/shared/_mobile_menu.html.erb
<div class="menu-mobile">
        <%# <div class="logo-mobile-menu">
            <img class = "d-block w-75" src ="https://res.cloudinary.com/dsmxleyf5/image/upload/v1613217013/vhp7i4i7d4darfxrd8by.png" alt="logo-relook-estehetique">
        </div> %>

    <nav class="navmenu2">
            <h4 class="text center", style="font-family: Montserrat" >RELOOK ESTHETIQUE</h4>
            <li><%= link_to "ACCUEIL", root_path%></li>
            <li><%= link_to "CONTACT", salons_path%></li>
            <li><%= link_to " PATRICIA SERIE", about_path%></li>
            <li><%= link_to "EPILATIONS", epilations_path %></li>

            <li><%= link_to " MASSAGES", massages_path %></li>

            <li><%= link_to "SOINS", soinvisages_path %></li>

            <li><%= link_to "MAQUILLAGE PERMANENT", maquillages_path %></li>

        </nav>

</div>

app/views/shared/_mobile_navbar.html.erb
<div class= "aboutaccueil-mobile">
  
  <ul class="navbar-nav mr-auto">
    <% if user_signed_in? %>
       <li class="nav-item dropdown">
        <%# <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %> 
        <div class ="avatar" id = "navbarDropdown" data-toggle="dropdown" ><%= current_user.email.capitalize[0] %></div>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
<!--           < % = render 'layouts/mini_cart', class: "dropdown-item" %>  -->
          <%= link_to link_to "Mon Caddie", carts_path, class: "dropdown-item" %>

          <%= link_to "Mes Commandes", orders_path, class: "dropdown-item" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
    <% else %>
      <li class="nav-item">
        <%= link_to new_user_session_path do %>
        <i class="fas fa-user"></i>
      <% end %>

       
      </li>

      
    <% end %>
  </ul>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
 <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= render 'layouts/mini_cart', class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_shopping_cart.html.erb
<div class="collapse navbar-collapse" id="navbarSupportedContent"></div>

<div class= "aboutaccueil">

  <li><%= link_to "Contact", salons_path%></li>
  <li><%= link_to " Patricia Serie", about_path%></li>
  <ul class="navbar-nav mr-auto">
    <% if user_signed_in? %>
       <li class="nav-item dropdown">
        <%# <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %> 
        <div class ="avatar" id = "navbarDropdown" data-toggle="dropdown" ><%= current_user.email.capitalize[0] %></div>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
<!--           < % = render 'layouts/mini_cart', class: "dropdown-item" %>  -->
          <%= link_to link_to "Mon Caddie", carts_path, class: "dropdown-item" %>

          <%= link_to "Mes Commandes", orders_path, class: "dropdown-item" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
    <% else %>
      <li class="nav-item">
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>

       
      </li>

      
    <% end %>
  </ul>
</div>

      
<%= link_to carts_path do %>
  <div class="cart-view">
      <i class="fas fa-shopping-cart">
        <div class="cart-inside">
          <%= current_order.order_items.size %>
        </div>
      </i>
  </div>
<% end %>