config/routes.rb
Rails.application.routes.draw do
  get 'reviews/index'
  get 'salons/index'
  #devise_for :users
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

  mount StripeEvent::Engine, at: '/stripe-webhooks'

  root to: 'pages#home'
  get "legal", to: 'pages#legal'
  get "about", to: 'pages#about'
  get "contact", to: 'pages#contact'
  resources :reviews do
    match '/scrape', to: 'reviews#scrape', via: :post, on: :collection
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


 resources :salons,  only: [:index]

  resources :epilations do
    resources :order_items, only: [:create, :update, :destroy]
  end

  resource :contacts, only: [:new, :create] do
    get "/thanks" => "contacts#thanks"
  end
  #resources :epilations, only: [:index, :show, :new, :edit, :update, :create, :destroy]
  # get "epilations", to: "epilations#index"
  # get "epilations/new", to: "epilations#new"
  # post "epilations", to: "epilations#create"
  # get "epilations/:id/edit", to: "epilations#edit"
  # patch "epilations/:id", to: "epilations#update"

  resources :massages do
    resources :order_items, only: [:create, :update, :destroy]
  end

  #resources :massages, only: [:index, :show, :new, :edit, :update, :create, :destroy]
  #get "massages", to: "massages#index"

  resources :maquillages do
    resources :order_items, only: [:create, :update, :destroy]
  end
  #resources :maquillages, only: [:index, :show, :new, :edit, :update, :create, :destroy]
  #get "maquillages", to: "maquillages#index"

  resources :soinvisages do
    resources :order_items, only: [:create, :update, :destroy]
  end
  #resources :soinvisages, only: [:index, :show, :new, :edit, :update, :create, :destroy]
  #get "soinvisages", to: "soinvisages#index"

  # Faut t'il plutot nester ?
  # resources :epilations, :massages, :maquillages, :soinvisages do
  #resources :order_items, only: [:create, :update, :destroy]
  # end
  resources :orders, only: [:index, :show, :destroy]

  resources :carts, only: [:index]
  resources :carts, only: [:new], as: :order do
    resources :payments, only: [:new]
  end

  # get '*unmatched_route', to: 'application#raise_not_found'
end

app/models/epilation.rb
class Epilation < ApplicationRecord
  attr_accessor :remove_photo


  belongs_to :user
  include Orderitemable
  has_one_attached :photo
  has_rich_text :rich_content
  monetize :price_cents
  validates :name, presence: true, uniqueness: true


end

app/controllers/epilations_controller.rb
class EpilationsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show]
  before_action :set_epilation, only: [:show, :edit, :update, :destroy]

  def home
  end

  def index

    @epilations = policy_scope(Epilation).sort_by { |m| [m.created_at] }.reverse!
    @epilations = @epilations.select { |epilation| epilation.name != "BON CADEAU" }
    @bc_epilation = Epilation.find_by(name: "BON CADEAU")

    @epilations_hommes=@epilations.select{ |epil| epil.category == "homme" }
    @epilations_femmes=@epilations.select{ |epil| epil.category == "femme" }

    @order_item = current_order.order_items.new
    @boncadeau = current_order.order_items.new
  end

  def new
    @epilation = Epilation.new
    authorize @epilation
  end

  def show
  end

  def create
    @epilation = Epilation.new(epilation_params)
    @epilation.user = current_user
    authorize @epilation
    if @epilation.save
      redirect_to epilations_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    purge_photo if !params[:epilation][:remove_photo].nil? && params[:epilation][:remove_photo].to_sym == :true
    @epilation.update(epilation_params)
    redirect_to epilation_path(@epilation)
  end

  def destroy
    authorize @epilation
    @epilation.destroy
    redirect_to epilations_path
  end

  def delete_attachment
    attachment = ActiveStorage::Attachment.find(params[:id])
    attachment.purge
    redirect_back(fallback_location: epilation_path(@epilation))
  end

  private

  def epilation_params
    params.require(:epilation).permit(:name, :remove_photo, :description, :user_id, :photo, :rich_content, :price_cents)
  end

  def set_epilation
    @epilation = Epilation.find(params[:id])
    authorize @epilation
  end

  def purge_photo
    @epilation.photo.purge
  end
end

app/views/epilations/_form.html copie.erb
<%= simple_form_for(@epilation) do |f| %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name, :label => "Nouvelle Prestation" %>
    <%= f.input :description, as: :text, :input_html => { :cols => 35, :rows => 6 } %>
    <%= f.input :price_cents, :label => "Prix" %>
    <%= f.rich_text_area :rich_content %>
    <%= f.input :photo, as: :file, label: "Ajoutez une photo" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :value => "Enregistrer", class: "btn btn-dark" %>
  </div>
<% end %>

app/views/epilations/_form.html.erb
<%= simple_form_for(@epilation) do |f| %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="presta-form-inputs">
    <% if @epilation.name == "" %>
      <%= f.input :name, :label => "Nouvelle Prestation" %>
    <% else%>
      <%= f.input :name, :label => "Nom" %>
    <% end %>
    <%= f.input :description, as: :text %>
    <%= f.input :price_cents, :label => "Prix" %>
  </div>
  <br/>

  <div class="presta-form-inputs col">
<!--     < %= f.input :description, :label => "Descrption" %>
 --><%= f.rich_text_area :rich_content %>

  </div>
  <br/>

  <div class="presta-form-inputs">
    <% if @epilation.photo.attached? %>
      <br/>
      <%= cl_image_tag @epilation.photo.key, height: 300, width: 400, crop: :fill %>
      <br/>
      <%= f.input :remove_photo, as: :boolean, label: "Supprimer la photo", checked_value: :true, unchecked_value: :false %>
    <% else %>
      <%= f.input :photo, as: :file, label: "Ajoutez une photo" %>
    <% end %>
  </div>
  <br/>

  <div class="form-actions">
    <%= f.button :submit, :value => "Enregistrer", class: "btn btn-dark" %>
  </div>

<% end %>

app/views/epilations/edit.html.erb
<div class="navmenu-presta">
  <div class="logo"></div>
  <li><%= link_to "EPILATIONS", epilations_path %></li>
  <li><%= link_to "MASSAGES", massages_path %></li>
  <li><%= link_to "SOINS DU VISAGE", soinvisages_path %></li>
  <li><%= link_to "MAQUILLAGE PERMANENT", maquillages_path %></li>
</div>

<div class="false-menu"></div>

<div class="under-menu">
  <h1 class="under-title"><%= link_to "Epilations", epilations_path %></h1>
  <span class="retour-accueil"><%= link_to "ACCUEIL", root_path %></span>
</div>

<div class="container">
<%= render 'form', model: @epilation %>
</div>

app/views/epilations/index.html.erb
<div class="navmenu-presta">
  <div class="logo"></div>

  <li><%= link_to "EPILATIONS", epilations_path %></li>
  <li><%= link_to "MASSAGES", massages_path %></li>
  <li><%= link_to "SOINS", soinvisages_path %></li>
  <li><%= link_to "MAQUILLAGE PERMANENT", maquillages_path %></li>
</div>

<div class="false-menu"></div>

<div class="under-menu">
<div class="presta-container">
  <h1 class="under-title">Epilations</h1>
  <div class = "contact-banner-presta"> <%=link_to "Je prends rendez-vous", new_contacts_path, class: "btn btn-ghost presta-button"%>  </div>
</div>  
  <span class="retour-accueil"><%= link_to "ACCUEIL", root_path %></span>
</div>

<div class="container">


 <%# <p>Épilation toutes zones pour les femmes.<br />
    Épilation Messieurs : Sourcils, Narines, Oreilles, Torse, Dos. <br /> %>

    <p>
      Pionnier et expert de l’épilation, PERRONT RIGOT répond à tous les besoins de façon ciblée et adaptée par ses différentes cires. Après chaque épilation, des soins « ralentisseurs de pousse de poils » et « spécial poils incarnés » sont utilisés.
    </p>
  <h3 class = "text-center sign">~</h3>
      <p>
A l’occasion d’un anniversaire, de Noël, ou tout simplement pour faire plaisir, offrez un moment de bien-être à ceux que vous aimez… <br />
  <h3 class = "text-center sign">~</h3>

<p>Deux choix s'offrent à vous <br />
Vous pouvez sélectionner un ou plusieurs de nos soins ci-dessous et les ajouter à votre panier en cliquant sur le bouton "Offrir".<br />
Vous préférez le bon cadeau montant libre ? Vous choisissez le montant de votre cadeau, à partir de 20€ en cliquant sur le bouton "Bon cadeau".<br />
Dans les deux cas le bénéficiaire pourra profiter de ses bons dans l’Institut Relook Esthétique.</p>

  <div class="makeup-container">
  
    <div class="card-wrapper">
  <h3 class = "text-center sign">~</h3>

    <div class="cards">

    <h3 class="presta-name free-price">Bon Cadeau</h3>
   <div class="presta-price">
   
   
     <!-- Button trigger modal -->
  <button type="button" class="bubbly-button" data-toggle="modal" data-target="#exampleModalCenter">
    Montant Libre
  </button>
  <!-- Modal -->
  <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">Choisissez votre montant</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <input id="ex1" data-slider-id='ex1Slider' type="text" data-slider-min="2" data-slider-max="78" data-slider-step="1" data-slider-value="5"/>
          <!-- <span id="ex1CurrentSliderValLabel"><span id="ex1SliderVal"></span></span> -->
        </div>
        <div class="modal-footer">
          <!-- <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button> -->
          <%= form_for([@bc_epilation, @order_item], remote: true) do |f| %>
           <%= f.hidden_field :orderitemable_type, value: "Epilation" %>
           <%= f.hidden_field :orderitemable_id, value: @bc_epilation.id %>
           <%= f.hidden_field :quantity, value: 1 %>
           <% @order_item = @boncadeau %>
           <% p @order_item %>
           <%= f.submit "Offrir", class: 'btn btn-ghost btn-sm' %>
          <% end %>
        <!-- <button type="button" class="btn btn-primary" data-dismiss="modal">Offrir</button> -->
        </div>
      </div>
    </div>
  </div>
  </div>
  
   </div>
    <h3 class = "text-center">~</h3>
   
      <h3>Epilation Femmes</h3>
      <% @epilations_femmes.each do |epilation| %>
        <div class="cards">
          <% if policy(Epilation).destroy? %>
            <p>
              <%= link_to epilation_path(epilation), method: :delete, data: { confirm: "Are you sure?" } do %>
                <i class="far fa-trash-alt"></i>
                <% end %>
            </p>
          <% end %>
          <div class="presta-name">
              <%= epilation.name %><%#<%= " " if epilation.description != "" %>
              <%#<%= epilation.description %><%= " " if epilation.price != "" %>
          </div>
          <div class="presta-price">
            <%= form_for([epilation, @order_item], remote: true) do |f| %>
              <%= f.hidden_field :orderitemable_type, value: "Epilation" %>
              <%= f.hidden_field :orderitemable_id, value: epilation.id %>
              <%= f.hidden_field :quantity, value: 1, min: 1, class: 'form-control' %>
              <%= humanized_money_with_symbol(epilation.price) %>
              <%= f.submit "Offrir", class: 'btn btn-ghost2 btn-sm' %>
            <% end %>
          </div>
          
        </div>
      <% end %>
      <h3>Epilation Hommes</h3>
      <% @epilations_hommes.each do |epilation| %>
        <div class="cards">
          <% if policy(Epilation).destroy? %>
            <p>
              <%= link_to epilation_path(epilation), method: :delete, data: { confirm: "Are you sure?" } do %>
                <i class="far fa-trash-alt"></i>
                <% end %>
            </p>
          <% end %>
          <div class="presta-name">
              <%= epilation.name %><%= " " if epilation.description != "" %>
              <%= epilation.description %><%= " " if epilation.price != "" %>
          </div>
          <div class="presta-price">
            <%= form_for([epilation, @order_item], remote: true) do |f| %>
              <%= f.hidden_field :orderitemable_type, value: "Epilation" %>
              <%= f.hidden_field :orderitemable_id, value: epilation.id %>
              <%= f.hidden_field :quantity, value: 1, min: 1, class: 'form-control' %>
              <%= humanized_money_with_symbol(epilation.price) %>
              <%= f.submit "Offrir", class: 'btn btn-ghost2 btn-sm' %>
            <% end %>
          </div>
          
        </div>
      <% end %>
    </div>
    <div class="epil-bann"></div>
  </div>
  <% if policy(Epilation).new? %>
    <p>
      <%= link_to "Nouvelle Prestation", new_epilation_path %>
    </p>
  <% end %>
</div>

app/views/epilations/new.html.erb
<%= render 'form', model: @epilation %>

app/views/epilations/show.html.erb
<div class="navmenu-presta">
  <div class="logo"></div>
  <li><%= link_to "EPILATIONS", epilations_path %></li>
  <li><%= link_to "MASSAGES", massages_path %></li>
  <li><%= link_to "SOINS DU VISAGE", soinvisages_path %></li>
  <li><%= link_to "MAQUILLAGE PERMANENT", maquillages_path %></li>
</div>
<div class="false-menu"></div>
<div class="under-menu">
  <h1 class="under-title"><%= link_to "Epilations", epilations_path %></h1>
  <h2><%= @epilation.name %></h2>
  <% if policy(Epilation).edit? %>
      <br/>
      <br/>
      <%= link_to edit_epilation_path(@epilation) do %>
        <i class="far fa-edit"></i>
      <% end %>
    <% end %>
  <span class="retour-accueil"><%= link_to "ACCUEIL", root_path %></span>
</div>
<div class = "container">
  <div class="cardsnoflex">
    <%= @epilation.description %>
    <br/>
    <%= @epilation.rich_content %>
    <% if @epilation.photo.attached? %>
      <br/>
      <%= cl_image_tag @epilation.photo.key, height: 300, width: 400, crop: :fill %>
    <% end %>
  </div>
</div>