config/routes.rb
Rails.application.routes.draw do
  get 'reviews/index'
  get 'salons/index'
  #devise_for :users
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

  mount StripeEvent::Engine, at: '/stripe-webhooks'

  root to: 'pages#home'
  get "legal", to: 'pages#legal'
  get "about", to: 'pages#about'
  get "contact", to: 'pages#contact'
  resources :reviews do
    match '/scrape', to: 'reviews#scrape', via: :post, on: :collection
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


 resources :salons,  only: [:index]

  resources :epilations do
    resources :order_items, only: [:create, :update, :destroy]
  end

  resource :contacts, only: [:new, :create] do
    get "/thanks" => "contacts#thanks"
  end
  #resources :epilations, only: [:index, :show, :new, :edit, :update, :create, :destroy]
  # get "epilations", to: "epilations#index"
  # get "epilations/new", to: "epilations#new"
  # post "epilations", to: "epilations#create"
  # get "epilations/:id/edit", to: "epilations#edit"
  # patch "epilations/:id", to: "epilations#update"

  resources :massages do
    resources :order_items, only: [:create, :update, :destroy]
  end

  #resources :massages, only: [:index, :show, :new, :edit, :update, :create, :destroy]
  #get "massages", to: "massages#index"

  resources :maquillages do
    resources :order_items, only: [:create, :update, :destroy]
  end
  #resources :maquillages, only: [:index, :show, :new, :edit, :update, :create, :destroy]
  #get "maquillages", to: "maquillages#index"

  resources :soinvisages do
    resources :order_items, only: [:create, :update, :destroy]
  end
  #resources :soinvisages, only: [:index, :show, :new, :edit, :update, :create, :destroy]
  #get "soinvisages", to: "soinvisages#index"

  # Faut t'il plutot nester ?
  # resources :epilations, :massages, :maquillages, :soinvisages do
  #resources :order_items, only: [:create, :update, :destroy]
  # end
  resources :orders, only: [:index, :show, :destroy]

  resources :carts, only: [:index]
  resources :carts, only: [:new], as: :order do
    resources :payments, only: [:new]
  end

  # get '*unmatched_route', to: 'application#raise_not_found'
end

app/models/soinvisage.rb
class Soinvisage < ApplicationRecord
  belongs_to :user
  include Orderitemable
  has_one_attached :photo
  has_rich_text :rich_content
  monetize :price_cents
  validates :name, presence: true, uniqueness: true
end

app/controllers/soinvisages_controller.rb
class SoinvisagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show]
  before_action :set_soinvisage, only: [:show, :edit, :update, :destroy]

  def home
  end

  def index
    @soinvisages = policy_scope(Soinvisage).sort_by { |m| [m.created_at] }.reverse!
    @soinvisages = @soinvisages.select { |soinvisage| soinvisage.name != "BON CADEAU" }
    @bc_soinvisage = Soinvisage.find_by(name: "BON CADEAU")
    @soinvisages_visages=@soinvisages.select{ |soin| soin.category == "Soins du visage" }
    @soinvisages_esths=@soinvisages.select{ |soin| soin.category == "Soins Esthétiques" }
    @order_item = current_order.order_items.new
    @boncadeau = current_order.order_items.new
  end

  def new
    @soinvisage = Soinvisage.new
    authorize @soinvisage
  end

  def show
  end

  def create
    @soinvisage = Soinvisage.new(soinvisage_params)
    @soinvisage.user = current_user
    authorize @soinvisage
    if @soinvisage.save
      redirect_to soinvisages_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    purge_photo if !params[:soinvisage][:remove_photo].nil? && params[:soinvisage][:remove_photo].to_sym == :true
    @soinvisage.update(soinvisage_params)
    redirect_to soinvisage_path(@soinvisage)
  end

  def destroy
    authorize @soinvisage
    @soinvisage.destroy
    redirect_to soinvisages_path
  end

  def delete_attachment
    attachment = ActiveStorage::Attachment.find(params[:id])
    attachment.purge
    redirect_back(fallback_location: soinvisage_path(@soinvisage))
  end

  private

  def soinvisage_params
    params.require(:soinvisage).permit(:name, :remove_photo, :description, :user_id, :photo, :rich_content, :price_cents)
  end

  def set_soinvisage
    @soinvisage = Soinvisage.find(params[:id])
    authorize @soinvisage
  end

  def purge_photo
    @soinvisage.photo.purge
  end
end

app/views/soinvisages/_form.html.erb
<%= simple_form_for(@soinvisage) do |f| %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="presta-form-inputs">
    <% if @soinvisage.name == "" %>
      <%= f.input :name, :label => "Nouvelle Prestation" %>
    <% else%>
      <%= f.input :name, :label => "Nom" %>
    <% end %>
    <%= f.input :description, as: :text %>
    <%= f.input :price_cents, :label => "Prix" %>
  </div>
  <br/>

  <div class="presta-form-inputs col">
<!--     < %= f.input :description, :label => "Descrption" %>
 --><%= f.rich_text_area :rich_content %>
  </div>
  <br/>

  <div class="presta-form-inputs">
    <% if @soinvisage.photo.attached? %>
      <br/>
      <%= cl_image_tag @soinvisage.photo.key, height: 300, width: 400, crop: :fill %>
      <br/>
      <%= f.input :remove_photo, as: :boolean, label: "Supprimer la photo", checked_value: :true, unchecked_value: :false %>
    <% else %>
      <%= f.input :photo, as: :file, label: "Ajoutez une photo" %>
    <% end %>
  </div>
  <br/>

  <div class="form-actions">
    <%= f.button :submit, :value => "Enregistrer", class: "btn btn-dark" %>
  </div>

<% end %>

app/views/soinvisages/edit.html.erb
<div class="navmenu-presta">
  <div class="logo"></div>
  <li><%= link_to "EPILATIONS", epilations_path %></li>
  <li><%= link_to "MASSAGES", massages_path %></li>
  <li><%= link_to "SOINS DU VISAGE", soinvisages_path %></li>
  <li><%= link_to "MAQUILLAGE PERMANENT", maquillages_path %></li>
</div>

<div class="false-menu"></div>

<div class="under-menu">
  <h1 class="under-title"><%= link_to "Soins", soinvisages_path %></h1>
  <span class="retour-accueil"><%= link_to "ACCUEIL", root_path %></span>
</div>

<div class="container">
<%= render 'form', model: @soinvisage %>
</div>

app/views/soinvisages/index.html.erb
<div class="navmenu-presta">
  <%# <li><%= link_to "ACCUEIL", root_path%>
  <%# </li> %>
  <%# <li><a href="#about">A PROPOS</a></li> %>

  <div class="logo"></div>
  <li><%= link_to "EPILATIONS", epilations_path %></li>
  <li><%= link_to "MASSAGES", massages_path %></li>
  <li><%= link_to "SOINS", soinvisages_path %></li>
  <li><%= link_to "MAQUILLAGE PERMANENT", maquillages_path %></li>
</div>

<div class="false-menu"></div>
<div class="under-menu">
<div class="presta-container">

  <h1 class="under-title">Soins</h1>
    <div class = "contact-banner-presta"> <%=link_to "Je prends rendez-vous", new_contacts_path, class: "btn btn-ghost presta-button"%>  </div>

</div>
  <span class="retour-accueil"><%= link_to "ACCUEIL", root_path %></span>
</div>

<div class="container">
 
  <p>
    Les soins spécifiques pour hommes, pour femmes et pour les juniors sont devenus des incontournables lorsque l'on souhaite prendre soin de sa peau.
Aidez votre peau à se préserver et à lutter contre les signes du temps avec notre gamme exclusive à l'aloe vera 100% bio.<br />
De nombreuses études ont démontré l'efficacité de ce trésor botanique qu'est l'aloe véra..
  </p>
    <h3 class = "text-center sign">~</h3>
      <p>
A l’occasion d’un anniversaire, de Noël, ou tout simplement pour faire plaisir, offrez un moment de bien-être à ceux que vous aimez… <br />
  <h3 class = "text-center sign">~</h3>

<p>Deux choix s'offrent à vous <br />
Vous pouvez sélectionner un ou plusieurs de nos soins ci-dessous et les ajouter à votre panier en cliquant sur le bouton "Offrir".<br />
Vous préférez le bon cadeau montant libre ? Vous choisissez le montant de votre cadeau, à partir de 20€ en cliquant sur le bouton "Bon cadeau".<br />
Dans les deux cas le bénéficiaire pourra profiter de ses bons dans l’Institut Relook Esthétique.</p>

  <div class="makeup-container">
    <div class="card-wrapper">
    <h3 class = "text-center sign">~</h3>

    <div class="cards">

    <h3 class="presta-name free-price">Bon Cadeau</h3>
   <div class="presta-price">
     <!-- Button trigger modal -->
  <button type="button" class="bubbly-button" data-toggle="modal" data-target="#exampleModalCenter">
    Montant libre
  </button>
  <!-- Modal -->
  <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">Choisissez votre montant</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <input id="ex1" data-slider-id='ex1Slider' type="text" data-slider-min="2" data-slider-max="78" data-slider-step="1" data-slider-value="5"/>
          <!-- <span id="ex1CurrentSliderValLabel"><span id="ex1SliderVal"></span></span> -->
        </div>
        <div class="modal-footer">
          <%= form_for([@bc_soinvisage, @order_item], remote: true) do |f| %>
           <%= f.hidden_field :orderitemable_type, value: "Soinvisage" %>
           <%= f.hidden_field :orderitemable_id, value: @bc_soinvisage.id %>
           <%= f.hidden_field :quantity, value: 1 %>
           <% @order_item = @boncadeau %>
           <% p @order_item %>
           <%= f.submit "Offrir", class: 'btn btn-ghost btn-sm' %>
          <% end %>
        <!-- <button type="button" class="btn btn-primary" data-dismiss="modal">Offrir</button> -->
        </div>
      </div>
    </div>
  </div>
  </div>
  
   </div>
    <h3 class = "text-center">~</h3>
      <h3>Soins du visage</h3>
      <% @soinvisages_visages.each do |soinvisage| %>
        <div class="cards">
          <% if policy(Soinvisage).destroy? %>
            <p>
              <%= link_to soinvisage_path(soinvisage), method: :delete, data: { confirm: "Are you sure?" } do %>
                <i class="far fa-trash-alt"></i>
              <% end %>
            </p>
          <% end %>
          <div class="presta-name">
              <%= soinvisage.name %><%#<%= " " if soinvisage.description != "" %>
              <%#<%= soinvisage.description %><%= " " if soinvisage.price != "" %>
          </div>
          <div class="presta-price">
            <%= form_for([soinvisage, @order_item], remote: true) do |f| %>
              <%= f.hidden_field :orderitemable_type, value: "Soinvisage" %>
              <%= f.hidden_field :orderitemable_id, value: soinvisage.id %>
              <%= f.hidden_field :quantity, value: 1, min: 1, class: 'form-control' %>
              <%= humanized_money_with_symbol(soinvisage.price) %>
              <%= f.submit "Offrir", class: 'btn btn-ghost2 btn-sm' %>
            <% end %>
          </div>
          
        </div>
      <% end %>
</div>
    <div class="soinvisage-bann">
      <img class="aloe-logo" src="https://res.cloudinary.com/dsmxleyf5/image/upload/v1618152192/bd80lj1g0br4g3gwa43q.png" alt="logo-aloevera">
    </div>

</div>

  <div class="makeup-container">
    <div class="card-wrapper">


      <h3>Soins Esthétiques</h3>
      <% @soinvisages_esths.each do |soinvisage| %>
        <div class="cards">
          <% if policy(Soinvisage).destroy? %>
            <p>
              <%= link_to soinvisage_path(soinvisage), method: :delete, data: { confirm: "Are you sure?" } do %>
                <i class="far fa-trash-alt"></i>
              <% end %>
            </p>
          <% end %>
          <div class="presta-name">
              <%= soinvisage.name %><%= " " if soinvisage.description != "" %>
              <%= soinvisage.description %><%= " " if soinvisage.price != "" %>
          </div>
          <div class="presta-price">
            <%= form_for([soinvisage, @order_item], remote: true) do |f| %>
              <%= f.hidden_field :orderitemable_type, value: "Soinvisage" %>
              <%= f.hidden_field :orderitemable_id, value: soinvisage.id %>
              <%= f.hidden_field :quantity, value: 1, min: 1, class: 'form-control' %>
              <%= humanized_money_with_symbol(soinvisage.price) %>
              <%= f.submit "Offrir", class: 'btn btn-ghost2 btn-sm' %>
            <% end %>
            </div>
           
          </div>
      <% end %>
    </div>
    <div class="manucure-bann">
    
    </div>

  </div>
  <% if policy(Soinvisage).new? %>
    <p>
      <%= link_to "Nouvelle Prestation", new_soinvisage_path %>
    </p>
  <% end %>
</div>

app/views/soinvisages/new.html.erb
<%= render 'form', model: @soinvisage %>
<%= link_to "Annuler", request.referer.present? ? request.referer : root_path %>

app/views/soinvisages/show.html.erb
<div class="navmenu-presta">
  <div class="logo"></div>
  <li><%= link_to "EPILATIONS", soinvisages_path %></li>
  <li><%= link_to "MASSAGES", soinvisages_path %></li>
  <li><%= link_to "SOINS DU VISAGE", soinvisages_path %></li>
  <li><%= link_to "MAQUILLAGE PERMANENT", soinvisages_path %></li>
</div>
<div class="false-menu"></div>
<div class="under-menu">
  <h1 class="under-title"><%= link_to "Soins", soinvisages_path %></h1>
  <h2><%= @soinvisage.name %></h2>
  <% if policy(Soinvisage).edit? %>
      <br/>
      <br/>
      <%= link_to edit_soinvisage_path(@soinvisage) do %>
       <i class="far fa-edit"></i>
      <% end %>
    <% end %>
  <span class="retour-accueil"><%= link_to "ACCUEIL", root_path %></span>
</div>
<div class = "container">
  <div class="cardsnoflex">
    <%= @soinvisage.description %>
    <br/>
    <%= @soinvisage.rich_content %>
    <% if @soinvisage.photo.attached? %>
      <br/>
      <%= cl_image_tag @soinvisage.photo.key, height: 300, width: 400, crop: :fill %>
    <% end %>
  </div>
</div>