config/routes.rb
Rails.application.routes.draw do
  get 'reviews/index'
  get 'salons/index'
  #devise_for :users
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

  mount StripeEvent::Engine, at: '/stripe-webhooks'

  root to: 'pages#home'
  get "legal", to: 'pages#legal'
  get "about", to: 'pages#about'
  get "contact", to: 'pages#contact'
  resources :reviews do
    match '/scrape', to: 'reviews#scrape', via: :post, on: :collection
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


 resources :salons,  only: [:index]

  resources :epilations do
    resources :order_items, only: [:create, :update, :destroy]
  end

  resource :contacts, only: [:new, :create] do
    get "/thanks" => "contacts#thanks"
  end
  #resources :epilations, only: [:index, :show, :new, :edit, :update, :create, :destroy]
  # get "epilations", to: "epilations#index"
  # get "epilations/new", to: "epilations#new"
  # post "epilations", to: "epilations#create"
  # get "epilations/:id/edit", to: "epilations#edit"
  # patch "epilations/:id", to: "epilations#update"

  resources :massages do
    resources :order_items, only: [:create, :update, :destroy]
  end

  #resources :massages, only: [:index, :show, :new, :edit, :update, :create, :destroy]
  #get "massages", to: "massages#index"

  resources :maquillages do
    resources :order_items, only: [:create, :update, :destroy]
  end
  #resources :maquillages, only: [:index, :show, :new, :edit, :update, :create, :destroy]
  #get "maquillages", to: "maquillages#index"

  resources :soinvisages do
    resources :order_items, only: [:create, :update, :destroy]
  end
  #resources :soinvisages, only: [:index, :show, :new, :edit, :update, :create, :destroy]
  #get "soinvisages", to: "soinvisages#index"

  # Faut t'il plutot nester ?
  # resources :epilations, :massages, :maquillages, :soinvisages do
  #resources :order_items, only: [:create, :update, :destroy]
  # end
  resources :orders, only: [:index, :show, :destroy]

  resources :carts, only: [:index]
  resources :carts, only: [:new], as: :order do
    resources :payments, only: [:new]
  end

  # get '*unmatched_route', to: 'application#raise_not_found'
end

app/models/maquillage.rb
class Maquillage < ApplicationRecord
  belongs_to :user
  include Orderitemable
  has_one_attached :photo
  has_rich_text :rich_content
  monetize :price_cents
  validates :name, presence: true, uniqueness: true
end

app/controllers/maquillages_controller.rb
class MaquillagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show]
  before_action :set_maquillage, only: [:show, :edit, :update, :destroy]

  def home
  end

  def index
    @maquillages = policy_scope(Maquillage).sort_by { |m| [m.created_at] }.reverse!
    @maquillages = @maquillages.select { |maquillage| maquillage.name != "BON CADEAU" }
    @bc_maquillage = Maquillage.find_by(name: "BON CADEAU")
    @order_item = current_order.order_items.new
    @boncadeau = current_order.order_items.new
  end

  def new
    @maquillage = Maquillage.new
    authorize @maquillage
  end

  def show
  end

  def create
    @maquillage = Maquillage.new(maquillage_params)
    @maquillage.user = current_user
    authorize @maquillage
    if @maquillage.save
      redirect_to maquillages_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    purge_photo if !params[:maquillage][:remove_photo].nil? && params[:maquillage][:remove_photo].to_sym == :true
    @maquillage.update(maquillage_params)
    redirect_to maquillage_path(@maquillage)
  end

  def destroy
    authorize @maquillage
    @maquillage.destroy
    redirect_to maquillages_path
  end

  def delete_attachment
    attachment = ActiveStorage::Attachment.find(params[:id])
    attachment.purge
    redirect_back(fallback_location: maquillage_path(@maquillage))
  end

  private

  def maquillage_params
    params.require(:maquillage).permit(:name, :remove_photo, :description, :user_id, :photo, :rich_content, :price_cents)
  end

  def set_maquillage
    @maquillage = Maquillage.find(params[:id])
    authorize @maquillage
  end

  def purge_photo
    @maquillage.photo.purge
  end
end

app/views/maquillages/_form.html.erb
<%= simple_form_for(@maquillage) do |f| %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="presta-form-inputs">
    <% if @maquillage.name == "" %>
      <%= f.input :name, :label => "Nouvelle Prestation" %>
    <% else%>
      <%= f.input :name, :label => "Nom" %>
    <% end %>
    <%= f.input :description, as: :text %>
    <%= f.input :price_cents, :label => "Prix" %>
  </div>
  <br/>

  <div class="presta-form-inputs col">
<!--     < %= f.input :description, :label => "Descrption" %>
 --><%= f.rich_text_area :rich_content %>
  </div>
  <br/>

  <div class="presta-form-inputs">
    <% if @maquillage.photo.attached? %>
      <br/>
      <%= cl_image_tag @maquillage.photo.key, height: 300, width: 400, crop: :fill %>
      <br/>
      <%= f.input :remove_photo, as: :boolean, label: "Supprimer la photo", checked_value: :true, unchecked_value: :false %>
    <% else %>
      <%= f.input :photo, as: :file, label: "Ajoutez une photo" %>
    <% end %>
  </div>
  <br/>

  <div class="form-actions">
    <%= f.button :submit, :value => "Enregistrer", class: "btn btn-dark" %>
  </div>

<% end %>

app/views/maquillages/edit.html.erb
<div class="navmenu-presta">
  <div class="logo"></div>
  <li><%= link_to "EPILATIONS", epilations_path %></li>
  <li><%= link_to "MASSAGES", massages_path %></li>
  <li><%= link_to "SOINS DU VISAGE", soinvisages_path %></li>
  <li><%= link_to "MAQUILLAGE PERMANENT", maquillages_path %></li>
</div>

<div class="false-menu"></div>

<div class="under-menu">
  <h1 class="under-title"><%= link_to "Maquillages", maquillages_path %></h1>
  <span class="retour-accueil"><%= link_to "ACCUEIL", root_path %></span>
</div>

<div class="container">
<%= render 'form', model: @maquillage %></div>
</div>

app/views/maquillages/index.html.erb
<div class="navmenu-presta">
  <%# <li><%= link_to "ACCUEIL", root_path%>
  <%# </li> %>
  <%# <li><a href="#about">A PROPOS</a></li> %>

  <div class="logo"></div>
  <li><%= link_to "EPILATIONS", epilations_path %></li>
  <li><%= link_to "MASSAGES", massages_path %></li>
  <li><%= link_to "SOINS", soinvisages_path %></li>
  <li><%= link_to "MAQUILLAGE PERMANENT", maquillages_path %></li>
</div>
<div class="false-menu"></div>
<div class="under-menu">
<div class="presta-container">

  <h1 class="under-title">Maquillage <br />
  Permanent</h1>
  <div class = "contact-banner-presta"> <%=link_to "Je prends rendez-vous", new_contacts_path, class: "btn btn-ghost presta-button"%>  </div>

</div>
  <span class="retour-accueil"><%= link_to "ACCUEIL", root_path %></span>
</div>
<div class="container">




  <p>Soyez sublime à tout moment de la journée grâce au maquillage permanent.
     Pour votre confort et votre sécurité, nous vous proposons un travail de qualité dans un cadre adapté avec du matériel et des pigments aux normes.
     Relook Esthétique s’engage à respecter les règles d’hygiène du ministère de la santé.
  </p>
    <h3 class = "text-center sign">~</h3>
      <p>
A l’occasion d’un anniversaire, de Noël, ou tout simplement pour faire plaisir, offrez un moment de bien-être à ceux que vous aimez… <br />
  <h3 class = "text-center sign">~</h3>

<p>Deux choix s'offrent à vous <br />
Vous pouvez sélectionner un ou plusieurs de nos soins ci-dessous et les ajouter à votre panier en cliquant sur le bouton "Offrir".<br />
Vous préférez le bon cadeau montant libre ? Vous choisissez le montant de votre cadeau, à partir de 20€ en cliquant sur le bouton "Bon cadeau".<br />
Dans les deux cas le bénéficiaire pourra profiter de ses bons dans l’Institut Relook Esthétique.</p>


  <div class="makeup-container">

    <div class="card-wrapper">
      <h3 class = "text-center sign">~</h3>

    <div class="cards">

    <h3 class="presta-name free-price">Bon Cadeau</h3>
   <div class="presta-price">


      <!-- Button trigger modal -->
  <button type="button" class="bubbly-button" data-toggle="modal" data-target="#exampleModalCenter">
    Montant libre
  </button><br /><br />
  <!-- Modal -->
  <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">Choisissez votre montant</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <input id="ex1" data-slider-id='ex1Slider' type="text" data-slider-min="2" data-slider-max="78" data-slider-step="1" data-slider-value="5"/>
          <!-- <span id="ex1CurrentSliderValLabel"><span id="ex1SliderVal"></span></span> -->
        </div>
        <%# <% @maquillages.each do |maquillage| %>
        <div class="modal-footer">
          <%= form_for([@bc_maquillage, @order_item], remote: true) do |f| %>
          <%= f.hidden_field :orderitemable_type, value: "Maquillage" %>
          <%= f.hidden_field :orderitemable_id, value: @bc_maquillage.id %>
          <%= f.hidden_field :quantity, value: 1 %>
          <% @order_item = @boncadeau %>
          <% p @order_item %>
          <%= f.submit "Offrir", class: 'btn btn-ghost btn-sm' %>
          <% end %>

          <!-- <button type="button" class="btn btn-primary" data-dismiss="modal">Offrir</button> -->
        </div>
        <%# <% end %>
      </div>
    </div>
  </div>
 </div>

   </div>
    <h3 class = "text-center">~</h3>
      <% @maquillages.each do |maquillage| %>
        <div class="cards">
          <% if policy(Maquillage).destroy? %>
            <p>
              <%= link_to maquillage_path(maquillage), method: :delete, data: { confirm: "Are you sure?" } do %>
                <i class="far fa-trash-alt"></i>
              <% end %>
            </p>
          <% end %>
          <div class="presta-name">
              <%= maquillage.name %><%#<%= " " if maquillage.description != "" %>
              <%#<%= maquillage.description %><%= " " if maquillage.price != "" %>
          </div>
          <div class="presta-price">
            <%= form_for([maquillage, @order_item], remote: true) do |f| %>
              <%= f.hidden_field :orderitemable_type, value: "Maquillage" %>
              <%= f.hidden_field :orderitemable_id, value: maquillage.id %>
              <%= f.hidden_field :quantity, value: 1, min: 1, class: 'form-control' %>
              <%= humanized_money_with_symbol(maquillage.price) %>
              <%= f.submit "Offrir", class: 'btn btn-ghost2 btn-sm' %>
            <% end %>
         </div>

        </div>
      <% end %>
    </div>
    <div class="makeup-bann"></div>
  </div>
  <% if policy(Maquillage).new? %>
    <p>
      <%= link_to "Nouvelle Prestation", new_maquillage_path %>
    </p>
  <% end %>
</div>

app/views/maquillages/new.html.erb
<%= render 'form', model: @maquillage %>

app/views/maquillages/show.html.erb
<div class="navmenu-presta">
  <div class="logo"></div>
  <li><%= link_to "EPILATIONS", maquillages_path %></li>
  <li><%= link_to "MASSAGES", massages_path %></li>
  <li><%= link_to "SOINS DU VISAGE", soinvisages_path %></li>
  <li><%= link_to "MAQUILLAGE PERMANENT", maquillages_path %></li>
</div>
<div class="false-menu"></div>
<div class="under-menu">
  <h1 class="under-title"><%= link_to "Maquillages", maquillages_path %></h1>
  <h2><%= @maquillage.name %></h2>
  <% if policy(Maquillage).edit? %>
      <br/>
      <br/>
      <%= link_to edit_maquillage_path(@maquillage) do %>
        <i class="far fa-edit"></i>
      <% end %>
    <% end %>
  <span class="retour-accueil"><%= link_to "ACCUEIL", root_path %></span>
</div>
<div class = "container">
  <div class="cardsnoflex">
    <%= @maquillage.description %>
    <br/>
    <%= @maquillage.rich_content %>
    <% if @maquillage.photo.attached? %>
      <br/>
      <%= cl_image_tag @maquillage.photo.key, height: 300, width: 400, crop: :fill %>
    <% end %>
  </div>
</div>